Add `.extensionKit` as the new `PBXProductType`
tuist/XcodeProj pull request #691
Opened 2022-06-25 02:11 UTC by mtj0928

### Short description 📝
From Xcode14 beta 1, `com.apple.product-type.extensionkit-extension` was introduced as the new productType.
The new productType is used for a new app extension like AppIntents Extension.

### Solution 📦
Added `.extensionKit` as the new case of `PBXProductType` in this PR, to support the new productType.

### Implementation 👩‍💻👨‍💻
- [x] Added `.extensionKit` as the new case of `PBXProductType`
- [x] Added `fileExtension` of `.extensionKit`
- [x] Add a new UnitTest for `.extensionKit`

2022-06-25 06:49 UTC, kwridan reviewed
Thanks for contributing this @mtj0928 

For consistency other product types (e.g. `appExtension`), I was thinking perhaps `.extensionKitExtension`? I appreciate the repeat of "extension" word is a bit odd 😅

2022-06-25 06:50 UTC, kwridan commented
@all-contributors add @mtj0928 for code

2022-06-26 01:50 UTC, mtj0928 commented
@kwridan 
Thank you for your comment!!

I actually considered the name at first , but I also felt it was a bit odd.
Would you like me to change the name `extensionKitExtension`?

2022-06-28 05:59 UTC, freddi-kit commented
I vote to rename as `extensionKitExtension` to make naming consistently to others (appExtension, tvExtension)

2022-06-28 06:02 UTC, kwridan approved these changes
Thinking through it some more, the concern I had was around the possibility of there being `extensionKit<SomethingElse>` by the structure of the product current product ID.

That said, we can start out with `.extensionKit` which is less odd, should any future products be added that extend this (e.g. `.extensionKitHost`) we could deprecate `.extensionKit` and re-introduce the specialised `.extensionKitExtension`.

So let's proceed with `.extensionKit`.

2022-06-28 06:04 UTC, freddi-kit approved these changes

2022-06-28 06:05 UTC, kwridan commented
cc: @tuist/core - any preference to the naming convention - I could see either option working, consistency vs oddness 😅

2022-06-28 16:28 UTC, fortmarek approved these changes

2022-06-28 19:14 UTC, kwridan requested changes
For visibility marking as request changes. thanks again!

2022-06-29 01:24 UTC, mtj0928 commented
Thank you for your discussion, I renamed the new case and pushed the changes😄

2022-06-29 06:16 UTC, kwridan approved these changes
Thanks @mtj0928

2022-06-29 06:44 UTC, merged

2022-06-30 07:26 UTC, kwridan commented
Let's wait till #694 is merged then we can do a release with a few of the Xcode 14 related items within it.